# 03 - DecisionTree
**Last Updated: 2022/04/12** <br>
**A decision tree model to predict the 6 sadness sub-emotions.**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree

In [2]:
# for tf-idf
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Eric\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
#Packages that are typically not included in Jupyter and might need to be installed.
try:
    import pandas_profiling as pp
except:
    !pip install ipywidgets
    !pip install pandas-profiling
    import pandas_profiling as pp

## Loading Dataset

In [4]:
# Read in the database and csv file
anno2_r_path = "./02-anno2_r.xlsx"    #2-annotations, researcher focussed
anno2_p_path = "./02-anno2_p.xlsx"    #2-annotations, participant focussed
anno3_path = "./02-anno3.xlsx"    #3-annotations, balanced

df = pd.read_excel(anno2_r_path)
df

ID                                              Tweet  ori_i  \
0      0                      Depression sucks! #depression  0.958   
1      1            Feeling worthless as always #depression  0.958   
2      2                        Feeling worthless as always  0.958   
3      3  Im think ima lay in bed all day and sulk. Life...  0.934   
4      4  So when I try I fail... and when I don't try.....  0.917   
..   ...                                                ...    ...   
269  269  Pops are joyless, soulless toys which look nea...  0.354   
270  270  Why is it that we rejoice at a birth and griev...  0.354   
271  271  Regret for the things we did can be tempered b...  0.354   
272  272                           In serious need of a nap  0.354   
273  273  First weekend of fall; let's see if I can stay...  0.333   

        anno1_e  anno1_i     anno2_e  anno2_i  
0     depressed        3   depressed        2  
1     depressed        4   depressed        1  
2     depressed        4   depressed        2  
3     depressed        5   depressed        4  
4     depressed        4  displeased        4  
..          ...      ...         ...      ...  
269  displeased        3  displeased        1  
270   depressed        3  displeased        2  
271        hurt        1      guilty        3  
272   depressed        4   depressed        1  
273   depressed        1  displeased        2  

[274 rows x 7 columns]

In [5]:
df_new = df[df['anno1_e'] == df['anno2_e']]
df_new.head()

ID                                              Tweet  ori_i    anno1_e  \
0   0                      Depression sucks! #depression  0.958  depressed   
1   1            Feeling worthless as always #depression  0.958  depressed   
2   2                        Feeling worthless as always  0.958  depressed   
3   3  Im think ima lay in bed all day and sulk. Life...  0.934  depressed   
5   5                  my life in one word is depressing  0.917  depressed   

   anno1_i    anno2_e  anno2_i  
0        3  depressed        2  
1        4  depressed        1  
2        4  depressed        2  
3        5  depressed        4  
5        3  depressed        3

In [6]:
#Quick check that all 6 sub-emotions are represented
df_new['anno1_e'].unique()

array(['depressed', 'displeased', 'grief', 'hurt', 'lonely', 'guilty'],
      dtype=object)

## tf-idf Embedding

In [7]:
# Removing Stopwords
english_stop_words = set(stopwords.words('english'))

In [8]:
## Applying tf-idf - To Map tweets to numerical vetors
vectorizer = TfidfVectorizer(stop_words = english_stop_words)
X = vectorizer.fit_transform(df_new['Tweet'])
X

<175x938 sparse matrix of type '<class 'numpy.float64'>'
	with 1482 stored elements in Compressed Sparse Row format>

In [9]:
df_with_features = pd.DataFrame(X.todense())
df_with_features

0    1    2    3    4    5    6    7    8    9    ...  928  929  930  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
170  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
171  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
172  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
173  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
174  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     931  932  933  934  935  936  937  
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
170  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
171  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
172  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
173  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
174  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[175 rows x 938 columns]

In [10]:
df_with_features['label'] = df_new['anno1_e'].values

## Decision Tree

In [11]:
dtree_model = DecisionTreeClassifier(max_depth = 10, random_state = 101) # 0.54 # Do better for depressed percision & displeased recall
X = df_with_features.drop(['label'], axis = 1)
y = df_with_features['label']
cross_val_predict(dtree_model, X, y, cv = 5)

C:\Users\Eric\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


array(['depressed', 'depressed', 'displeased', 'displeased', 'displeased',
       'depressed', 'displeased', 'depressed', 'depressed', 'depressed',
       'displeased', 'depressed', 'displeased', 'depressed', 'displeased',
       'displeased', 'displeased', 'depressed', 'displeased', 'depressed',
       'displeased', 'depressed', 'displeased', 'displeased', 'grief',
       'displeased', 'displeased', 'displeased', 'depressed', 'depressed',
       'depressed', 'depressed', 'displeased', 'displeased', 'displeased',
       'displeased', 'depressed', 'displeased', 'displeased',
       'displeased', 'hurt', 'displeased', 'displeased', 'displeased',
       'displeased', 'displeased', 'displeased', 'displeased',
       'depressed', 'displeased', 'displeased', 'displeased',
       'displeased', 'displeased', 'displeased', 'depressed',
       'displeased', 'displeased', 'displeased', 'displeased',
       'displeased', 'displeased', 'displeased', 'displeased',
       'displeased', 'displeased', 

## Accuracy Scores

In [12]:
## Apllying 5-fold cross validation
predict_svc = pd.Series(cross_val_predict(dtree_model, X, y, cv = 5))

## Generating Confusoin Matrix
conf_matrix_svc = confusion_matrix(y, predict_svc, labels = ['displeased', 'depressed', 'hurt', 'lonely', 'grief', 'guilty'])
print(conf_matrix_svc)

[[70  3  3  0  1  0]
 [46 28  1  0  1  0]
 [ 7  1  0  0  0  0]
 [ 6  0  0  0  0  0]
 [ 6  0  1  0  0  0]
 [ 1  0  0  0  0  0]]


C:\Users\Eric\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


In [13]:
## Classification Report
target_names = ['displeased', 'depressed', 'hurt', 'lonely', 'grief', 'guilty']
print(classification_report(y, predict_svc, target_names = target_names))

              precision    recall  f1-score   support

  displeased       0.88      0.37      0.52        76
   depressed       0.51      0.91      0.66        77
        hurt       0.00      0.00      0.00         7
      lonely       0.00      0.00      0.00         1
       grief       0.00      0.00      0.00         8
      guilty       0.00      0.00      0.00         6

    accuracy                           0.56       175
   macro avg       0.23      0.21      0.20       175
weighted avg       0.61      0.56      0.51       175



C:\Users\Eric\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [14]:
## Prediction
sentence = ["she has depression"]
X_test1 = vectorizer.transform(sentence)
#X_test1

clf = dtree_model.fit(X, y)
dtree_model.predict(X_test1.todense())

array(['depressed'], dtype=object)

## Visualization

In [15]:
#TODO: for choosing colors on the decision tree figure: https://stackoverflow.com/questions/70437840/

plt.figure(figsize=(50,25))

plot_tree(dtree_model,
          feature_names = X.columns,
          class_names = y,
          filled=True,
         )
#tree.plot_tree(dtree_model)
#plt.show()

plt.title("Decision Tree", fontdict=({'fontsize':30}))
plt.savefig("Decision_Tree_Visualization.png")